### ISSUE TITLE
Liquid Exception: tweet tag was never closed in CHANGELOG.md

### ISSUE THREAD

**Issue by jasongraham** [octopress/social#2]
I encountered an amusing bug when running `octopress docs` with this gem enabled.  It appears the line with "{% tweet %}" in the change log gets choked on.
# Conditions:
- Ruby Version: ruby 2.0.0p576 (2014-09-19) [x86_64-linux]
- Octopress Version: 3.0.5
- octopress-social version: 1.4.4
# Steps to Reproduce:
- `octopress new /some/dir`
- add to _config.yml

```
gems:
  - octopress-social
```
- `octopress docs`
# Result:

```
$ octopress docs -t
  Liquid Exception: tweet tag was never closed in CHANGELOG.md
/home/grahjm2a/.gem/ruby/2.0.0/gems/liquid-2.6.2/lib/liquid/block.rb:88:in `assert_missing_delimitation!': tweet tag was never closed (Liquid::SyntaxError)
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/liquid-2.6.2/lib/liquid/block.rb:49:in `parse'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/liquid-2.6.2/lib/liquid/tag.rb:10:in `initialize'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/octopress-social-1.4.4/lib/octopress-social/twitter.rb:116:in `initialize'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/liquid-2.6.2/lib/liquid/block.rb:28:in `new'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/liquid-2.6.2/lib/liquid/block.rb:28:in `parse'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/liquid-2.6.2/lib/liquid/document.rb:5:in `initialize'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/liquid-2.6.2/lib/liquid/template.rb:59:in `new'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/liquid-2.6.2/lib/liquid/template.rb:59:in `parse'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/liquid-2.6.2/lib/liquid/template.rb:46:in `parse'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:106:in `render_liquid'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:233:in `do_layout'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:350:in `do_layout'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/octopress-tag-helpers-1.0.6/lib/octopress-tag-helpers/hooks.rb:9:in `do_layout'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/jekyll-2.5.3/lib/jekyll/page.rb:122:in `render'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:298:in `block in render'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `each'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `render'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:197:in `render'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:51:in `process'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/octopress-3.0.5/lib/octopress/commands/docs.rb:33:in `serve_docs'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/octopress-3.0.5/lib/octopress/commands/docs.rb:16:in `block (2 levels) in init_with_program'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
    from /home/grahjm2a/.gem/ruby/2.0.0/gems/octopress-3.0.5/bin/octopress:8:in `<top (required)>'
    from /home/grahjm2a/.gem/ruby/2.0.0/bin/octopress:23:in `load'
    from /home/grahjm2a/.gem/ruby/2.0.0/bin/octopress:23:in `<main>'
```

**Comment by imathis** [comment]
I've just released `1.4.5` with your fix in. Thanks!
